# Generated by Django 4.2.2 on 2023-07-30 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='repeat_password',
            field=models.CharField(default='', max_length=40),
        ),
    ]
