# Generated by Django 4.2.2 on 2023-07-31 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_remove_gender_user_delete_age_delete_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='avatar',
            field=models.ImageField(blank=True, default='imgs/index/monalisa.jpg', null=True, upload_to='avatar/'),
        ),
    ]
