# Generated by Django 4.2.2 on 2023-07-18 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('item_created', models.DateField()),
                ('item_price', models.IntegerField()),
                ('item_description', models.CharField(max_length=999)),
                ('item_genre', models.PositiveSmallIntegerField(choices=[(1, 'Paintings'), (2, 'Sculptures'), (3, 'Nfts'), (4, 'Handcraft (Wood, Metal, etc)'), (5, 'Other')], default=1)),
                ('item_material', models.PositiveSmallIntegerField(choices=[(1, 'Digital Asset'), (2, 'Wood'), (3, 'Stone'), (4, 'Metal'), (5, 'Canvas & Paint'), (6, 'Ceramics'), (7, 'Clay'), (9, 'Others')], default=5)),
                ('item_image', models.ImageField(upload_to='')),
                ('item_stock', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
